name: urban_flora
description: "Urban field guide powered by Gemini. Isar & Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  # UI, Fonts & Assets
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Hardware & Services
  camera: ^0.12.1
  geolocator: ^13.0.1
  path_provider: ^2.1.4

  # Firebase Cloud & Auth
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  go_router: ^18.0.1
  dio: ^5.11.1
  image_picker: ^1.2.3
  firebase_ai: ^4.0.0
  firebase_app_check: ^0.4.8
  url_launcher: ^6.3.2
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  isar_community_generator: ^3.3.2
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/